# Generated by Django 3.2.8 on 2021-11-13 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('child_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='childplaces',
        ),
        migrations.AlterField(
            model_name='child',
            name='studyLevel',
            field=models.CharField(choices=[('1ST', 'First Year'), ('2ND', 'Second Year')], default='1ST', max_length=3),
        ),
        migrations.AlterField(
            model_name='place',
            name='attitude',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='child',
            table='child',
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parent',
        ),
        migrations.AlterModelTable(
            name='place',
            table='Place',
        ),
        migrations.CreateModel(
            name='ChildPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_app.child')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_app.place')),
            ],
            options={
                'db_table': 'child_place',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='children',
            field=models.ManyToManyField(through='child_app.ChildPlace', to='child_app.Child'),
        ),
    ]
