# Generated by Django 3.2.8 on 2021-11-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_app', '0003_rename_idparent_child_parent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place',
            table='place',
        ),
    ]
