# Generated by Django 3.2.8 on 2021-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_app', '0004_alter_place_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='attitude',
        ),
        migrations.AddField(
            model_name='place',
            name='lattitude',
            field=models.DecimalField(decimal_places=6, default=38.8951, max_digits=9),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-77.0364, max_digits=9),
        ),
    ]
