# Generated by Django 3.2.8 on 2021-11-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_app', '0005_auto_20211113_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='childplace',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
